apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - name: deliveries
          image: deliveries:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: deliveries-service
spec:
  selector:
    app: deliveries
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
